### ISSUE TITLE
Use `claim_id` to index objects in the database instead of permanent_uri

### ISSUE THREAD

**Issue by osilkin98** [ocornoc/lbry-comments#29]
I'm not really sure why we use the `permanent_uri` as opposed to the `claim_id` since `claim_id` is just the unique hash that we would want.

**Comment by ocornoc** [comment]
`claim_id` isn't a hash, it's an [SQLite3 primary key](https://www.sqlite.org/autoinc.html). It is used in the _underlying_ SQLite3 claim trackers because it is useful for the B-Tree structure that SQLite3 employs.

We use `permanent_uri` as the _public-facing_ index because it is unique and the same across servers.

The necessary problem with numeric comment IDs is that they are specific to any server instance, even if the two servers share or merge databases. That is in fact one of the only guarantees of numeric comment IDs: they refer unambiguously to a comment _only at the time of the comment ID's request_.

This problem is avoidable with claim trackers, and, as such, consistency is sacrificed for basic functionality.
